[pytest]
pythonpath = .
testpaths = tests
env =
    RAW_DIR=./tmp_test_data/raw
    CHROMA_DIR=./tmp_test_data/chroma
    METADATA_DIR=./tmp_test_data/metadata
    DOCUMENTS_REGISTRY_PATH=./tmp_test_data/metadata/documents.json
    HF_HOME=./tmp_test_data/hf_cache